/*
* generated by Xtext
*/
package org.softlang.xtestgen.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ConfigAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/softlang/xtestgen/parser/antlr/internal/InternalConfig.tokens");
	}
}
