/*
 * generated by Xtext
 */
package org.softlang.xtestgen.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractConfigValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.softlang.xtestgen.config.ConfigPackage.eINSTANCE);
		return result;
	}
}
