/*
 * generated by Xtext
 */
package org.softlang.xtestgen;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ConfigRuntimeModule extends org.softlang.xtestgen.AbstractConfigRuntimeModule {

}
