/*
 * generated by Xtext
 */
package org.softlang.xtestgen.ui.contentassist

import org.softlang.xtestgen.ui.contentassist.AbstractConfigProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ConfigProposalProvider extends AbstractConfigProposalProvider {
}
