/*
* generated by Xtext
*/
package org.softlang.xtestgen;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ConfigUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.softlang.xtestgen.ui.internal.ConfigActivator.getInstance().getInjector("org.softlang.xtestgen.Config");
	}
	
}
