/*
 * generated by Xtext
 */
package org.softlang.xtestgen.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.softlang.xtestgen.ui.internal.ConfigActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ConfigExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ConfigActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ConfigActivator.getInstance().getInjector(ConfigActivator.ORG_SOFTLANG_XTESTGEN_CONFIG);
	}
	
}
